"use client"
import { Inter } from "next/font/google";
import "./globals.css";

import { RainbowProvider } from "@/context/RainbowKitContext";
import { ContractFuncProvider } from "@/context/ContractFuncWegmiContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowProvider>
          <ContractFuncProvider>
            {children}
          </ContractFuncProvider>
        </RainbowProvider>
      </body>
    </html>
  );
}
